### ISSUE TITLE
One assignment too many

### ISSUE THREAD

**Issue by warpech** [Juicy/enlighted-link#2]
It looks like this line has one assignment too many: https://github.com/Juicy/enlighted-link/blob/226bbeb53bdf6ae923b47cd75b076fa70e0b0dfa/enlighted-link.html#L17

I guess it should be

```
const link = this.link || document.createElement('link');
```

**Comment by tomalec** [comment]
Not really, as I want to assign `this.link` as well. So it's like
```js
this.link = this.link || document.createElement('link'); 
const link = this.link;
```

**Comment by warpech** [comment]
Ah... ok! 

Some parenthesis would make it easier for me to read it:

```js
const link = this.link = (this.link || document.createElement('link')); 
``` 

I am not a big fan of code golfing in real-world projects, but some disagree: https://www.linusakesson.net/programming/kernighans-lever/index.php
